{% set data= load_setup_py_data() %}
package:
  name: ts-atdome
  version: {{ environ.get('GIT_DESCRIBE_TAG', "default") }}_{{ environ.get('GIT_BUILD_STR', "none") }}
#  version: {{ environ.get('GIT_DESCRIBE_TAG', environ.get('TS_VERSION', "default")) }}_{{ environ.get('GIT_BUILD_STR', "none") }}

source:
  path: ../

build:
  script: python -m pip install --ignore-installed .
  skip: True #[win]

test:
  requires:
    - pytest
    - pytest-flake8
    - pytest-cov
    - asynctest
    - ts-salobj
#  commands:
#    - py.test

requirements:
  host:
    - python
    - pip
    - setuptools_scm
    - setuptools
    - pytest-runner
  run:
    - python
    - setuptools
    - setuptools_scm
    - ts-salobj
    - ts-simactuators
